version: '3.8'

services:
   basket.api:
     container_name: lde.basket.api
     build:
       context: .
       dockerfile: Basket/Basket.Host/Dockerfile
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5003
       - Authorization__Authority=http://www.alevelwebsite.com:5002
       - Redis__Host=www.alevelwebsite.com:6380
       - Redis__CacheTimeout=24:00:00
       - PathBase=http://www.alevelwebsite.com:5003
     depends_on:
       - redis
     ports:
       - 5003:5003
   catalog.api:
     container_name: lde.catalog.api
     build:
       context: .
       dockerfile: Catalog/Catalog.Host/Dockerfile
     environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5000
        - ConnectionString=server=postgres;port=5432;database=devices;uid=postgres;password=postgres;
        - PathBase=http://www.alevelwebsite.com:5000
        - Authorization__Authority=http://www.alevelwebsite.com:5002
     depends_on:
       - postgres
     ports:
       - 5000:5000
   identityserver:
     container_name: lde.identityserver
     build:
       context: .
       dockerfile: IdentityServer/IdentityServer/Dockerfile
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5002
       - MvcUrl=http://www.alevelwebsite.com
       - CatalogApi=http://www.alevelwebsite.com:5000
       - BasketApi=http://www.alevelwebsite.com:5003
     ports:
       - 5002:5002
   nginx:
     build:
       context: .
       dockerfile: Web/SPA/Dockerfile
       args:
         REACT_APP_AUTH_URL: http://www.alevelwebsite.com:5002
         REACT_APP_IDENTITY_CLIENT_ID: mvc_pkce
         REACT_APP_IDENTITY_CLIENT_SECRET: secret
         REACT_APP_REDIRECT_URL: http://www.alevelwebsite.com/signin-oidc
         REACT_APP_SILENT_REDIRECT_URL: http://www.alevelwebsite.com/silentrenew
         REACT_APP_LOGOFF_REDIRECT_URL: http://www.alevelwebsite.com/logout/callback
         REACT_APP_BASE_API_URL: http://www.alevelwebsite.com/api
         REACT_APP_ROUTE_CATALOG: :5000/api/v1/CatalogBff
         REACT_APP_ROUTE_BASKET: :5003/api/v1/BasketBff
     container_name: lde.nginx
     ports:
       - 80:80
     volumes:
       - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
       - ./Proxy/assets:/var/www/assets
   pgadmin4:
     image: dpage/pgadmin4
     container_name: lde.pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: user@domain.com
       PGADMIN_DEFAULT_PASSWORD: postgres
     depends_on:
       - postgres
     ports:
       - 8001:80 
   postgres:
     image: postgres
     container_name: lde.postgres
     environment:
       POSTGRES_PASSWORD: postgres
     ports:
      - 5433:5432
   redis:
     image: redis
     container_name: lde.redis
     ports:
       - 6380:6379
networks:
  dockernet:
    external: true